"""Встроенный (авторский) корпус знаний: дескрипторы грейдов и заметки по темам. Позволяет конвейеру работать
без внешнего корпуса. Лицензия — как у проекта."""

BUILTIN_NOTES: list[dict] = [
    {"path": "grades/intern", "title": "Ожидания от Intern", "grade": "intern", "languages": ["python", "java", "sql"],
     "topics": ["basics"], "text": "Intern: базовый синтаксис, переменные и типы, циклы и условия, простые коллекции, простые запросы SELECT с фильтрацией и сортировкой. Самостоятельно решает учебные задачи, нуждается в наставнике."},
    {"path": "grades/junior", "title": "Ожидания от Junior", "grade": "junior", "languages": ["python", "java", "sql"],
     "topics": ["basics", "collections"], "text": "Junior: уверенно работает с коллекциями, функциями и классами, понимает ссылки и копирование, исключения, базовое ООП. В SQL — JOIN, GROUP BY, HAVING, агрегаты. Пишет простые тесты, читает чужой код."},
    {"path": "grades/middle", "title": "Ожидания от Middle", "grade": "middle", "languages": ["python", "java", "sql"],
     "topics": ["design", "performance"], "text": "Middle: самостоятельно проектирует модули, знает замыкания, генераторы, итераторы, потоки и асинхронность, коллекции и их сложность. В SQL — подзапросы, CTE, оконные функции, индексы и чтение плана запроса. Покрывает код тестами."},
    {"path": "grades/senior", "title": "Ожидания от Senior", "grade": "senior", "languages": ["python", "java", "sql"],
     "topics": ["concurrency", "architecture"], "text": "Senior: отвечает за архитектурные решения, конкурентность и согласованность данных, профилирование и оптимизацию, наблюдаемость. В SQL — островки и разрывы, условная агрегация, транзакции и изоляция, устранение узких мест."},
    {"path": "grades/lead", "title": "Ожидания от Lead", "grade": "lead", "languages": ["python", "java", "sql"],
     "topics": ["architecture", "process"], "text": "Lead: определяет технические стандарты команды, управляет рисками и компромиссами, планирует эволюцию архитектуры и миграции без простоя, выстраивает процессы ревью, тестирования и эксплуатации."},
    {"path": "topics/sql-window", "title": "Оконные функции в SQL", "grade": "middle", "languages": ["sql"], "topics": ["sql_window"],
     "text": "Оконные функции ROW_NUMBER, RANK, SUM OVER, AVG OVER с PARTITION BY и ORDER BY считают значение по окну строк, не схлопывая результат. Типовые задачи: топ-N в группе, накопительные итоги, сравнение со средним по группе, предыдущее значение через LAG."},
    {"path": "topics/sql-islands", "title": "Островки и разрывы", "grade": "senior", "languages": ["sql"], "topics": ["sql_window"],
     "text": "Задача об островках: найти серии подряд идущих дат активности. Приём: вычесть из даты номер строки ROW_NUMBER в разбиении по пользователю; одинаковая разность задаёт одну серию. Применяется для анализа удержания и непрерывной активности."},
    {"path": "topics/sql-joins", "title": "JOIN и агрегаты", "grade": "junior", "languages": ["sql"], "topics": ["sql_joins_aggregation"],
     "text": "INNER JOIN оставляет совпавшие строки, LEFT JOIN сохраняет все строки левой таблицы. GROUP BY группирует, HAVING фильтрует группы по агрегатам, WHERE — строки до группировки. Анти-соединение: NOT EXISTS или LEFT JOIN с проверкой IS NULL."},
    {"path": "topics/sql-slow-query", "title": "Диагностика медленных запросов", "grade": "senior", "languages": ["sql"], "topics": ["sql_schema"],
     "text": "Начинайте с EXPLAIN ANALYZE: ищите полное сканирование и неверные оценки строк. Проверьте индексы, порядок столбцов, селективность, функции над индексируемым столбцом, устаревшую статистику, лишние JOIN и SELECT *. Для пагинации используйте keyset."},
    {"path": "topics/python-copy", "title": "Копирование и изменяемые аргументы", "grade": "junior", "languages": ["python"], "topics": ["collections_algorithms"],
     "text": "Изменяемые значения по умолчанию создаются один раз при определении функции. Присваивание не копирует объект; copy делает поверхностную копию, deepcopy — глубокую. Замыкания связывают переменную, а не значение, поэтому в цикле нужен аргумент по умолчанию."},
    {"path": "topics/python-async", "title": "Асинхронность и GIL", "grade": "senior", "languages": ["python"], "topics": ["concurrency"],
     "text": "asyncio даёт конкурентность для задач ввода-вывода; блокирующий вызов в корутине останавливает весь цикл событий. Для CPU-bound нагрузки нужны процессы, так как GIL не позволяет потокам исполнять байткод параллельно. Потокобезопасность, гонки, очереди и пулы воркеров."},
    {"path": "topics/python-cache", "title": "Кэш в памяти", "grade": "middle", "languages": ["python", "java"], "topics": ["caching"],
     "text": "Кэш с ограничением размера: словарь плюс порядок использования (OrderedDict, связный список). Политики вытеснения LRU, FIFO, TTL. Потокобезопасность, защита от cache stampede, метрики hit rate и evictions."},
    {"path": "topics/java-semantics", "title": "Семантика Java", "grade": "junior", "languages": ["java"], "topics": ["oop_design"],
     "text": "Целочисленное деление усекается к нулю, остаток имеет знак делимого. Переполнение int происходит по модулю 2^32. Integer кэшируется в диапазоне от -128 до 127, поэтому == для больших значений даёт false. Конкатенация строк слева направо. Арифметика над char даёт int."},
    {"path": "topics/java-concurrency", "title": "Многопоточность в Java", "grade": "senior", "languages": ["java"], "topics": ["concurrency"],
     "text": "Модель памяти Java: отношения happens-before через synchronized, volatile, запуск потока. volatile даёт видимость, но не атомарность. ConcurrentHashMap, атомарные классы, пулы потоков, виртуальные потоки для блокирующего ввода-вывода."},
    {"path": "topics/rest-service", "title": "REST-сервисы", "grade": "middle", "languages": ["python", "java"], "topics": ["rest_api"],
     "text": "REST-сервис: ресурсы и методы, коды ответов, пагинация и фильтрация, валидация входа, формат ошибок, идемпотентность, версионирование, тесты API, метрики и логирование."},
    {"path": "topics/rate-limit", "title": "Ограничение частоты запросов", "grade": "senior", "languages": ["python", "java"], "topics": ["rate_limit"],
     "text": "Ограничитель частоты: token bucket, sliding window, fixed window. Состояние клиентов, очистка устаревших записей, атомарность в конкурентной среде, общее хранилище при нескольких инстансах, ответ 429 и заголовок Retry-After."},
    {"path": "topics/large-files", "title": "Обработка больших файлов", "grade": "senior", "languages": ["python", "java"], "topics": ["large_data"],
     "text": "Большие файлы читают потоково, без загрузки целиком. Для подсчёта уникальных значений при ограниченной памяти применяют битовые карты, внешнюю сортировку, разбиение на партиции и приближённые структуры вроде HyperLogLog."},
]
